//先思考单个对象
/*var str*/
var data = [
    {
        name:'白羊座',
        time:'3.21-4.19'
    }
    ,{
        name:'金牛座',
        time:'4.20-5.20'
    }
    ,{
        name:'双子座',
        time:'5.21-6.21'
    }
    ,{
        name:'巨蟹座',
        time:'6.22-7.22'
    }
    ,{
        name:'狮子座',
        time:'7.23-8.22'
    }
    ,{
        name:'处女座',
        time:'8.23-9.22'
    }
    ,{
        name:'天秤座',
        time:'9.23-10.23'
    }
    ,{
        name:'天蝎座',
        time:'10.24-11.22'
    }
    ,{
        name:'射手座',
        time:'11.23-12.21'
    }
    ,{
        name:'摩羯座',
        time:'12.22-1.19'
    }
    ,{
        name:'水瓶座',
        time:'1.20-2.18'
    }
    ,{
        name:'双鱼座',
        time:'2.19-3.20'
    }
];
 var xingzuo = function() {
     this.__init__();
 }
